# Generated by Django 3.2.4 on 2021-06-03 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raffle', '0002_auto_20210603_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffletickets',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='raffletickets',
            unique_together={('user', 'event')},
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
